apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: guestbook
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/evandro-abreu/argocd.git
    targetRevision: HEAD
    path: proj1
  destination:
    server: https://kubernetes.default.svc
    namespace: proj1

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true  

